using System.Text;
using Microsoft.EntityFrameworkCore;
using ReadMeApp.Data;
using ReadMeApp.Models;

namespace ReadMeApp.Services;

public class ReadmeExportService : IReadmeExportService
{
    private readonly ReadmeDbContext _context;

    public ReadmeExportService(ReadmeDbContext context)
    {
        _context = context;
    }

    public async Task<string> GenerateReadmeMarkdownAsync()
    {
        var readingBooks = await _context.UserBooks
            .Include(ub => ub.Book)
            .Where(ub => ub.Status == ReadingStatus.Reading)
            .ToListAsync();

        var completedBooks = await _context.UserBooks
            .Include(ub => ub.Book)
            .Where(ub => ub.Status == ReadingStatus.Completed)
            .OrderByDescending(ub => ub.CompletedDate)
            .Take(5)
            .ToListAsync();

        var recentNotes = await _context.ReadingNotes
            .Include(n => n.UserBook)
            .ThenInclude(ub => ub!.Book)
            .OrderByDescending(n => n.CreatedAt)
            .Take(3)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine("<!-- Read.me Reading Journal Export -->");
        sb.AppendLine("### 📖 My Reading Journal (`Read.me`)");
        sb.AppendLine();
        sb.AppendLine("> *\"A reader lives a thousand lives before he dies.\" — George R.R. Martin*");
        sb.AppendLine();

        // Reading section
        sb.AppendLine("#### 🚀 Currently Reading");
        if (readingBooks.Count == 0)
        {
            sb.AppendLine("- *현재 읽고 있는 책이 없습니다. 새 책을 추가해 보세요!*");
        }
        else
        {
            foreach (var ub in readingBooks)
            {
                var book = ub.Book!;
                var pct = ub.ProgressPercentage;
                var bar = GenerateProgressBar(pct);
                sb.AppendLine($"- **{book.Title}** by {book.Author}");
                sb.AppendLine($"  - Progress: `{bar}` **{pct}%** ({ub.CurrentPage} / {book.TotalPages}p)");
            }
        }
        sb.AppendLine();

        // Completed section
        sb.AppendLine("#### ✅ Recently Completed");
        if (completedBooks.Count == 0)
        {
            sb.AppendLine("- *아직 완독한 책이 없습니다.*");
        }
        else
        {
            sb.AppendLine("| Title | Author | Rating | Completed Date |");
            sb.AppendLine("| :--- | :--- | :---: | :---: |");
            foreach (var ub in completedBooks)
            {
                var stars = ub.Rating.HasValue ? new string('★', ub.Rating.Value) : "-";
                var dateStr = ub.CompletedDate?.ToString("yyyy-MM-dd") ?? "-";
                sb.AppendLine($"| {ub.Book!.Title} | {ub.Book.Author} | {stars} | {dateStr} |");
            }
        }
        sb.AppendLine();

        // Notable quotes section
        if (recentNotes.Count > 0)
        {
            sb.AppendLine("#### 💡 Memorable Quotes & Thoughts");
            foreach (var note in recentNotes)
            {
                sb.AppendLine($"> \"{note.Quote}\"");
                sb.AppendLine($"> — *{note.UserBook?.Book?.Title}* (p.{note.PageNumber})");
                sb.AppendLine();
                if (!string.IsNullOrWhiteSpace(note.Thought))
                {
                    sb.AppendLine($"  💭 **Note**: {note.Thought.Trim()}");
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("---");
        sb.AppendLine($"*Generated by [Read.me](https://github.com/dh1180/Read.md) at {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC*");

        return sb.ToString();
    }

    private static string GenerateProgressBar(int percentage)
    {
        int totalBlocks = 10;
        int filled = Math.Clamp((int)Math.Round(percentage / 10.0), 0, totalBlocks);
        int empty = totalBlocks - filled;
        return new string('█', filled) + new string('░', empty);
    }
}
