using System.Text;
using Microsoft.EntityFrameworkCore;
using ReadMeApp.Data;
using ReadMeApp.Models;

namespace ReadMeApp.Services;

public class ReadmeExportService : IReadmeExportService
{
    private readonly ReadmeDbContext _context;

    public ReadmeExportService(ReadmeDbContext context)
    {
        _context = context;
    }

    public async Task<string> GenerateReadmeMarkdownAsync(string reviewerName)
    {
        var reviews = await _context.UserBooks
            .Include(ub => ub.Book)
            .Where(ub => ub.ReviewerName == reviewerName &&
                         ub.Status == ReadingStatus.Completed &&
                         ub.Content != null &&
                         ub.Content != "")
            .OrderByDescending(ub => ub.CreatedAt)
            .Take(10)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine("<!-- Read.me Reading Log Export -->");
        sb.AppendLine("### 📖 My Reading Log");
        sb.AppendLine();

        if (reviews.Count == 0)
        {
            sb.AppendLine("- 아직 작성된 독서록이 없습니다.");
        }
        else
        {
            sb.AppendLine("| 도서명 | 저자 | 별점 | 날짜 |");
            sb.AppendLine("| :--- | :--- | :---: | :---: |");
            foreach (var review in reviews)
            {
                var stars = new string('★', review.Rating) + new string('☆', 5 - review.Rating);
                sb.AppendLine($"| **{review.Book?.Title ?? "제목 없음"}** | {review.Book?.Author ?? "-"} | {stars} | {review.ReadDate:yyyy-MM-dd} |");
            }

            var quotes = reviews.Where(r => !string.IsNullOrWhiteSpace(r.Quote)).Take(5).ToList();
            if (quotes.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("#### 기억하고 싶은 문장");
                foreach (var review in quotes)
                {
                    sb.AppendLine($"> \"{review.Quote}\"");
                    sb.AppendLine($"> — *{review.Book?.Title}*");
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("---");
        sb.AppendLine($"*Generated by [Read.me](https://github.com/dh1180/Read.me) at {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC*");
        return sb.ToString();
    }
}
