using System.Text;
using Microsoft.EntityFrameworkCore;
using ReadMeApp.Data;
using ReadMeApp.Models;

namespace ReadMeApp.Services;

public class ReadmeExportService : IReadmeExportService
{
    private readonly ReadmeDbContext _context;

    public ReadmeExportService(ReadmeDbContext context)
    {
        _context = context;
    }

    public async Task<string> GenerateReadmeMarkdownAsync()
    {
        var reviews = await _context.UserBooks
            .Include(ub => ub.Book)
            .OrderByDescending(ub => ub.CreatedAt)
            .Take(10)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine("<!-- Read.me Reading Log Export -->");
        sb.AppendLine("### 📖 My Reading Log (`Read.me`)");
        sb.AppendLine();
        sb.AppendLine("> *\"책을 읽는다는 것은 다른 사람의 머리로 생각하는 것이다. 그러나 그 속에서 자신만의 생각을 발견해야 한다.\"*");
        sb.AppendLine();

        // Reviews section
        sb.AppendLine("#### 📚 내가 기록한 독서록");
        if (reviews.Count == 0)
        {
            sb.AppendLine("- *아직 작성된 독서록이 없습니다. 첫 번째 독서록을 작성해 보세요!*");
        }
        else
        {
            sb.AppendLine("| 도서명 | 저자 | 별점 | 작성자 | 날짜 |");
            sb.AppendLine("| :--- | :--- | :---: | :---: | :---: |");
            foreach (var r in reviews)
            {
                var stars = new string('★', r.Rating) + new string('☆', 5 - r.Rating);
                var dateStr = r.ReadDate.ToString("yyyy-MM-dd");
                var title = r.Book?.Title ?? "제목 없음";
                var author = r.Book?.Author ?? "-";
                sb.AppendLine($"| **{title}** | {author} | {stars} | {r.ReviewerName} | {dateStr} |");
            }
            sb.AppendLine();

            sb.AppendLine("#### 💡 기억하고 싶은 책 속 한 문장 (Quotes)");
            foreach (var r in reviews.Where(r => !string.IsNullOrWhiteSpace(r.Quote)).Take(5))
            {
                sb.AppendLine($"> \"{r.Quote}\"");
                sb.AppendLine($"> — *{r.Book?.Title}* (by {r.ReviewerName})");
                if (!string.IsNullOrWhiteSpace(r.Summary))
                {
                    sb.AppendLine($"  💭 **한줄평**: {r.Summary.Trim()}");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("---");
        sb.AppendLine($"*Generated by [Read.me](https://github.com/dh1180/Read.md) at {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC*");

        return sb.ToString();
    }
}
